version: '3'
services:
  composer:
    image: composer:latest
    volumes:
      - ./../.:/app
    command: composer install
      
  nodejs:
    image: node:latest
    volumes:
      - ./../.:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev && npm run watch"
      
  php:
    build: ./php
    volumes:
      - ./../.:/app
    working_dir: /app
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - 8000:8000
    depends_on:
        - nodejs