version: '3'
services:
  composer:
    image: composer:latest
    volumes:
      - ./../.:/app
    command: composer install
      
  nodejs:
    image: node:latest
    volumes:
      - ./../.:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev && npm run watch"
    depends_on:
      - composer
      
  php:
    image: php:7.2
    volumes:
      - ./../.:/app
    entrypoint:
      - php
      - /app/artisan
      - serve
      - --host=0.0.0.0
      - --port=8000
    ports:
      - 80:8000
    depends_on:
          - composer
          - nodejs